/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BodyImage = {
  _type: "bodyImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  layout: "contained" | "wide" | "full";
};

export type Callout = {
  _type: "callout";
  tone: "note" | "tip" | "warning";
  text: string;
};

export type Youtube = {
  _type: "youtube";
  url: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & BodyImage)
    | ({
        _key: string;
      } & Code)
    | ({
        _key: string;
      } & Youtube)
    | ({
        _key: string;
      } & Callout)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BodyImage
  | Callout
  | Youtube
  | Seo
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) {  _id,  title,  slug,  excerpt,  mainImage,  publishedAt}
export type AllPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
}>;

// Source: lib/queries.ts
// Variable: latestPostsQuery
// Query: *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) [0...$count] {  _id,  title,  slug,  excerpt,  mainImage,  publishedAt}
export type LatestPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
}>;

// Source: lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && publishedAt <= now() && slug.current == $slug][0]{    _id,    title,    slug,    excerpt,    mainImage,    publishedAt,    body[]{      ...,      markDefs[]{        ...,        _type == "link" => { href }      }    },    seo  }
export type PostBySlugQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          href: string;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "bodyImage";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        layout: "contained" | "full" | "wide";
        markDefs: null;
      }
    | {
        _key: string;
        _type: "callout";
        tone: "note" | "tip" | "warning";
        text: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "youtube";
        url: string;
        caption?: string;
        markDefs: null;
      }
  >;
  seo: Seo | null;
} | null;

// Source: lib/queries.ts
// Variable: allPostSlugsQuery
// Query: *[_type == "post" && publishedAt <= now()]{ "slug": slug.current, publishedAt }
export type AllPostSlugsQueryResult = Array<{
  slug: string;
  publishedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  excerpt,\n  mainImage,\n  publishedAt\n}\n': AllPostsQueryResult;
    '\n  *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) [0...$count] {\n  _id,\n  title,\n  slug,\n  excerpt,\n  mainImage,\n  publishedAt\n}\n': LatestPostsQueryResult;
    '\n  *[_type == "post" && publishedAt <= now() && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage,\n    publishedAt,\n    body[]{\n      ...,\n      markDefs[]{\n        ...,\n        _type == "link" => { href }\n      }\n    },\n    seo\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "post" && publishedAt <= now()]{ "slug": slug.current, publishedAt }\n': AllPostSlugsQueryResult;
  }
}
